const OA="https://api.openalex.org";
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const idOf=id=>String(id||"").split("/").pop();
async function oa(path,params={}){const u=new URL(OA+path);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u);if(!r.ok)throw new Error(`OpenAlex request failed (${r.status})`);return r.json()}
function normAuthor(a){const i=(a.last_known_institutions||[])[0];return{id:idOf(a.id),url:a.id,name:a.display_name,institution:i?.display_name||"Institution not supplied",orcid:a.ids?.orcid||a.orcid,works:+(a.works_count||0),citations:+(a.cited_by_count||0),h:+(a.summary_stats?.h_index||0),i10:+(a.summary_stats?.i10_index||0)}}
async function search(){const q=$("query").value.trim();if(q.length<2){setStatus("Enter at least two characters.",true);return}setStatus("Searching OpenAlex author index…");$("author-results").innerHTML="";try{const d=await oa("/authors",{search:q,"per-page":6});if(!d.results.length)throw new Error("No author matches returned");const rows=d.results.map(normAuthor);$("author-results").innerHTML=rows.map((a,i)=>`<button class="author-card" data-i="${i}"><b>${esc(a.name)}</b><span>${esc(a.institution)}</span><span>${a.works.toLocaleString()} works · ${a.citations.toLocaleString()} citations · h ${a.h}</span></button>`).join("");document.querySelectorAll(".author-card").forEach(b=>b.onclick=()=>analyze(rows[+b.dataset.i]));setStatus(`${rows.length} candidates retrieved. Select the correct identity.`)}catch(e){setStatus(e.message,true)}}
async function analyze(selected){setStatus(`Retrieving live works and longitudinal history for ${selected.name}…`);$("author-results").innerHTML="";try{const [raw,wd]=await Promise.all([oa(`/authors/${selected.id}`),oa("/works",{filter:`author.id:${selected.id}`,sort:"publication_date:desc","per-page":50,select:"id,doi,display_name,publication_year,publication_date,cited_by_count,type,primary_topic,open_access"})]);const author=normAuthor(raw);const works=wd.results.map(w=>({title:w.display_name||"Untitled",year:w.publication_year,date:w.publication_date,citations:+(w.cited_by_count||0),doi:w.doi,type:w.type,topic:w.primary_topic?.display_name,domain:w.primary_topic?.domain?.display_name,oa:!!w.open_access?.is_oa}));const metrics=calculate(raw,author,works);render(author,works,metrics);setStatus(`Live OpenAlex retrieval complete: ${works.length} recent records parsed and longitudinal indicators calculated.`)}catch(e){setStatus(`${e.message}. No metrics or AI output were generated.`,true)}}
function change(a,b){return b===0?(a===0?null:100):Math.round((a-b)/b*1000)/10}
function calculate(raw,a,works){const now=new Date().getUTCFullYear();const yearly=(raw.counts_by_year||[]).filter(x=>x.year>=now-11&&x.year<=now).sort((x,y)=>x.year-y.year).map(x=>({year:x.year,works:+x.works_count,citations:+x.cited_by_count}));const recent=yearly.filter(x=>x.year<now&&x.year>=now-5),prior=yearly.filter(x=>x.year>=now-10&&x.year<now-5);const sum=(xs,k)=>xs.reduce((n,x)=>n+x[k],0);const topics={};works.filter(w=>w.topic).forEach(w=>topics[w.topic]=(topics[w.topic]||0)+1);return{...a,yearly,recentWorks:sum(recent,"works"),priorWorks:sum(prior,"works"),recentCites:sum(recent,"citations"),priorCites:sum(prior,"citations"),pubChange:change(sum(recent,"works"),sum(prior,"works")),citeChange:change(sum(recent,"citations"),sum(prior,"citations")),oaShare:works.length?Math.round(works.filter(w=>w.oa).length/works.length*1000)/10:0,topics:Object.entries(topics).sort((a,b)=>b[1]-a[1]).slice(0,5),now}}
function ai(m){const f={publication_momentum:Math.max(-1,Math.min(2,m.pubChange||0)/100),citation_momentum:Math.max(-1,Math.min(2,m.citeChange||0)/100),h_index_scale:Math.min(m.h/100,1.5),recent_output_scale:Math.min(m.recentWorks/100,2)};const w={ACCELERATING:{bias:-.15,publication_momentum:1.35,citation_momentum:1.05,h_index_scale:.25,recent_output_scale:.35},STABLE:{bias:.35,publication_momentum:-.15,citation_momentum:.05,h_index_scale:.15,recent_output_scale:.1},WATCH:{bias:-.1,publication_momentum:-1.1,citation_momentum:-.65,h_index_scale:-.1,recent_output_scale:-.2}};const l={};for(const [k,s] of Object.entries(w))l[k]=s.bias+Object.entries(f).reduce((n,[q,v])=>n+s[q]*v,0);const peak=Math.max(...Object.values(l)),e=Object.fromEntries(Object.entries(l).map(([k,v])=>[k,Math.exp(v-peak)])),tot=Object.values(e).reduce((a,b)=>a+b),p=Object.fromEntries(Object.entries(e).map(([k,v])=>[k,Math.round(v/tot*1000)/10])),label=Object.keys(p).sort((a,b)=>p[b]-p[a])[0];return{f,p,label,prob:p[label]}}
function fmt(v){if(v===null)return"not computable";return `${Math.abs(v).toFixed(1)}% ${v>=0?"increase":"decrease"}`}
function render(a,works,m){$("dashboard").hidden=false;$("author-name").textContent=a.name;$("author-meta").textContent=`${a.institution}${a.orcid?" · ORCID "+a.orcid:""}`;$("source-link").href=a.url;const cards=[["Works",a.works],["Citations",a.citations],["h-index",a.h],["i10-index",a.i10],["Recent 5y works",m.recentWorks],["Open access sample",m.oaShare+"%"]];$("metrics").innerHTML=cards.map(([k,v])=>`<div class="metric"><span>${k}</span><strong>${typeof v==="number"?v.toLocaleString():v}</strong></div>`).join("");renderChart(m.yearly);$("window").innerHTML=`<div><strong>Publication monitoring</strong><p>${m.priorWorks} → ${m.recentWorks} works · <b>${fmt(m.pubChange)}</b></p><small>Prior five years versus recent five completed years</small></div><div><strong>Citation monitoring</strong><p>${m.priorCites.toLocaleString()} → ${m.recentCites.toLocaleString()} citations · <b>${fmt(m.citeChange)}</b></p><small>Citations received in the same windows</small></div>`;$("retrieved-at").textContent="Retrieved "+new Date().toLocaleString();$("sample-note").textContent=`Latest ${works.length} records`;$("publications").innerHTML=works.slice(0,8).map(w=>`<div class="publication"><span>${w.year||"—"}</span><b>${esc(w.title)}</b><span>${w.citations.toLocaleString()} citations${w.doi?" · DOI":""}</span></div>`).join("");const x=ai(m);$("ai-label").textContent=x.label;$("ai-prob").textContent=`${x.prob}% model probability`;const top=m.topics?.[0]?.[0]||"no dominant topic in the retrieved sample";$("ai-text").textContent=`The bounded model classifies the monitored trajectory as ${x.label}. This is grounded in a ${fmt(m.pubChange)} in five-year publication output, a ${fmt(m.citeChange)} in citations received across the same monitoring windows, h-index ${m.h}, and ${m.recentWorks} works in the recent completed window. The most frequent topic in the retrieved publication sample is ${top}.`;$("features").innerHTML=Object.entries(x.f).map(([k,v])=>`<div class="feature"><span>${k.replaceAll("_"," ")}</span><strong>${v.toFixed(3)}</strong></div>`).join("");$("dashboard").scrollIntoView({behavior:"smooth"})}
function renderChart(rows){const maxW=Math.max(1,...rows.map(r=>r.works)),maxC=Math.max(1,...rows.map(r=>r.citations));$("chart").innerHTML=rows.map(r=>`<div class="bar-group" title="${r.year}: ${r.works} works, ${r.citations} citations"><div class="bar works" style="height:${r.works/maxW*90}%"></div><div class="bar cites" style="height:${r.citations/maxC*90}%"></div><label>${r.year}</label></div>`).join("")}
function setStatus(s,bad=false){$("status").textContent=s;$("status").style.borderColor=bad?"#d32f4b":"#1769e0"}
$("search").onclick=search;$("query").onkeydown=e=>{if(e.key==="Enter")search()};
